name: Linux

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  placeholderjob:
    name: "Name of the job!"

    runs-on:
      - ubuntu-latest

    steps:
      - name: dummy
        run: |
          echo "This is only a placeholder!"
          exit 1
