name: MacOS

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    runs-on:
      - macos-latest

    steps:
      - name: dummy
        run: |
          echo "This is only a placeholder!"
          exit 1
