name: Windows

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  placeholderjob:
    name: "Build MSVC-Solution"

    runs-on:
      - windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: debug
        run: |
          msbuild --version
          exit 1
