name: Windows

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  placeholderjob:
    name: "Build MSVC-Solution"

    runs-on:
      - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup Solution
        working-directory: ${{runner.workspace}}/scripts/windows

      - name: Build
        working-directory: ${{runner.workspace}}
        run: |
          dir
          msbuild --version
          exit 1
